# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 04:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bookname',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='book',
            name='printversion',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publicationdate',
        ),
        migrations.AddField(
            model_name='book',
            name='pubdate',
            field=models.DateField(default=datetime.datetime(2016, 11, 11, 4, 7, 32, 729303, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='version',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=128),
        ),
    ]
