# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20161111_1207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
