# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='material',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pubdate',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='book',
            name='version',
        ),
    ]
